displayName=Player Indicators True Tile
author=willzero123
description=Adds true tile highlights to Player Indicators
tags=player indicators,true tile
version=1.0.0
plugins=com.playerindicatorstruetile.PlayerIndicatorsTrueTilePlugin
build=standard