displayName=Player Indicators True Tile
author=willzero123
description=Adds true-tile highlighting to Player Indicators while using its player categories and colors
tags=player indicators,true tile
version=1.0.0
plugins=com.playerindicatorstruetile.PlayerIndicatorsTrueTilePlugin
build=standard