displayName=True Tile Player Indicators
author=willzero123
description=Adds true tile highlights to Player Indicators. Disabled in PvP.
tags=player indicators,true tile
version=1.0.0
plugins=com.truetileplayerindicators.TrueTilePlayerIndicatorsPlugin
build=standard